import express from 'express'
import fs from 'fs'
import path from 'path'
import { exec } from 'child_process'
import { requireAuth } from './auth.js'
import { userWorkspace, safeResolve } from '../lib/paths.js'
import { emitUser } from '../lib/events.js'
import { audit } from '../lib/auditLog.js'
import { User } from '../lib/db.js'

const router = express.Router()
const GITHUB_API = 'https://api.github.com'

function run(cmd, cwd) {
  return new Promise((resolve) => exec(cmd, { cwd, timeout: 120000, maxBuffer: 1024 * 1024 * 8 }, (err, stdout, stderr) =>
    resolve({ code: err ? 1 : 0, out: String(stdout || ''), err: String(stderr || '') })
  ))
}

function emit(email, stage, message) {
  emitUser(email, { type: 'deploy_progress', stage, message })
}

/** فحص بصيغة الإنسان: بعد النشر نعالج الرابط ونتأكد أن الموقع يحيا */
async function verifyLive(email, url) {
  if (!url || !/^https:\/\//.test(url)) return
  const probe = async () => {
    try {
      const ctl = new AbortController()
      const to = setTimeout(() => ctl.abort(), 9000)
      const r = await fetch(url, { signal: ctl.signal, redirect: 'follow' })
      clearTimeout(to)
      return r.status
    } catch {
      return null
    }
  }
  for (let i = 0; i < 6; i++) {
    const code = await probe()
    if (code && code >= 200 && code < 500) {
      emit(email, 'verified', `فحص الرابط حيًا ✓ (رمز ${code})`)
      emitUser(email, { type: 'deploy_verified', url })
      return
    }
    await new Promise((r) => setTimeout(r, 12000))
  }
  emit(email, 'verify_wait', 'حرر GitHub Pages المشروع — الرابط سيتم الإعلان عنه خلال دقيقة تقريبًا')
}

function slugify(s) {
  return String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'ghennai-project'
}

/** مستودع موجود لحساب نفس المالك؟ عند التكرار نحدّث نفس الرابط الدائم بدل مستودع جديد */
async function existingOwnedRemote(projectDir, owner) {
  const r = await run('git remote get-url origin', projectDir)
  const u = r.out.trim()
  if (!u) return null
  const m = u.match(/github\.com[/:]([\w-]+)\/([\w.-]+?)(?:\.git)?$/)
  if (m && m[1] === owner) return { owner: m[1], repo: m[2].replace(/\.git$/, '') }
  return null
}

async function ghAvailable() {
  try {
    const { code } = await run('gh auth status', process.cwd())
    return code === 0
  } catch {
    return false
  }
}

router.get('/status', requireAuth, async (req, res) => {
  const email = req.user?.email
  const gh = await ghAvailable()
  const token = User.getSetting(email, 'github_token') || process.env.GITHUB_TOKEN || ''
  res.json({ hasToken: !!token, ghAvailable: gh })
})

router.post('/token', requireAuth, (req, res) => {
  const token = req.body?.token
  if (!token) return res.status(400).json({ error: 'token required' })
  User.setSetting(req.user.email, 'github_token', String(token).trim())
  res.json({ ok: true })
})

router.post('/', requireAuth, async (req, res) => {
  const email = req.user?.email
  const name = req.user?.name || email?.split('@')[0] || 'user'
  const ws = userWorkspace(email)
  let projectDir = ws
  const project = String(req.body?.project || '.')
  try {
    if (project && project !== '.' && project !== '~') {
      const p = safeResolve(ws, project.replace(/^~\/?/, ''))
      if (fs.statSync(p).isDirectory()) projectDir = p
    }
  } catch { projectDir = ws }

  let repoName = slugify(project === '.' ? `${name}-ghennai` : path.basename(project) || `${name}-ghennai`)
  let token = User.getSetting(email, 'github_token') || process.env.GITHUB_TOKEN || ''

  emit(email, 'init', 'إعداد المستودع محليًا…')
  const host = email?.split('@')[0]?.replace(/[^a-zA-Z0-9_\-]/g, '') || 'user'

  try {
    const gitInit = await run(`git init -b main && git add -A && git -c user.email="${host}@ghennai.local" -c user.name="${name}" commit -m "Generated by Ghennai" --allow-empty`, projectDir)
    if (gitInit.code !== 0 && !gitInit.err.includes('nothing to commit')) {
      emit(email, 'init', `git init: ${gitInit.err.trim().slice(0, 120)}`)
    } else {
      emit(email, 'init', 'تم تهيئة git والالتزام محليًا ✓')
    }

    let owner, url, pagesUrl = null
    if (token) {
      emit(email, 'gh', 'إنشاء المستودع على GitHub…')
      const who = await fetch(`${GITHUB_API}/user`, { headers: { Authorization: `token ${token}` } })
      if (!who.ok) throw new Error('توكن GitHub غير صالح — تحقق من الإعدادات')
      const whoJson = await who.json()
      owner = whoJson.login

      const owned = await existingOwnedRemote(projectDir, owner)
      if (owned) {
        emit(email, 'gh', `تحديث نفس المستودع «${owned.repo}» — رابطك الدائم يبقى كما هو ✓`)
        repoName = owned.repo
        url = `https://github.com/${owner}/${owned.repo}`
        pagesUrl = `https://${owner}.github.io/${owned.repo}/`
        const repush = await run(`git push -u origin main --force`, projectDir)
        if (repush.code !== 0) throw new Error(`فشل الدفع للتحديث: ${repush.err.trim().slice(0, 180)}`)
      } else {

      const create = await fetch(`${GITHUB_API}/user/repos`, {
        method: 'POST',
        headers: { Authorization: `token ${token}`, 'Content-Type': 'application/json', 'User-Agent': 'ghennai' },
        body: JSON.stringify({ name: repoName, description: 'Built by Ghennai — autonomous AI agent', private: false }),
      })
      if (create.status === 422) {
        const renamed = `${repoName}-${Date.now().toString(36).slice(-6)}`
        emit(email, 'gh', `الاسم «${repoName}» مستخدم — جارٍ النشر باسم فريد «${renamed}»…`)
        const retry = await fetch(`${GITHUB_API}/user/repos`, {
          method: 'POST',
          headers: { Authorization: `token ${token}`, 'Content-Type': 'application/json', 'User-Agent': 'ghennai' },
          body: JSON.stringify({ name: renamed, description: 'Built by Ghennai — autonomous AI agent', private: false }),
        })
        if (retry.status !== 201) {
          const txt = await retry.text()
          throw new Error(`فشل إنشاء المستودع باسم فريد (${retry.status}): ${txt.slice(0, 160)}`)
        }
        repoName = renamed
      } else if (create.status !== 201) {
        throw new Error(`فشل إنشاء المستودع (${create.status}): ${(await create.text()).slice(0, 160)}`)
      }
      emit(email, 'gh', `تم إنشاء المستودع «${repoName}» ✓`)

      const remote = `https://x-access-token:${token}@github.com/${owner}/${repoName}.git`
      const push = await run(`git remote remove origin 2>/dev/null; git remote add origin ${remote} && git push -u origin main --force`, projectDir)
      if (push.code !== 0) throw new Error(`فشل الدفع: ${push.err.trim().slice(0, 180)}`)
      url = `https://github.com/${owner}/${repoName}`
      pagesUrl = `https://${owner}.github.io/${repoName}/`
      }
    } else if (await ghAvailable()) {
      emit(email, 'gh', 'الدفع عبر GitHub CLI…')
      const ghLogin = (await run('gh api user --jq .login 2>/dev/null', projectDir)).out.trim()
      const owned = ghLogin ? await existingOwnedRemote(projectDir, ghLogin) : null
      if (owned) {
        emit(email, 'gh', `تحديث نفس المستودع «${owned.repo}» — رابطك الدائم يبقى كما هو ✓`)
        repoName = owned.repo
        owner = owned.owner
        url = `https://github.com/${owner}/${owned.repo}`
        pagesUrl = `https://${owner}.github.io/${owned.repo}/`
        const repush = await run(`git push -u origin main --force`, projectDir)
        if (repush.code !== 0) throw new Error(`فشل الدفع للتحديث: ${repush.err.trim().slice(0, 180)}`)
      } else {
      let ghName = repoName
      const makeGh = async (nm) =>
        run(`git remote remove origin 2>/dev/null; gh repo create ${nm} --public --source=. --push`, projectDir)
      let push = await makeGh(ghName)
      if (push.code !== 0 && /already (exists|taken)/i.test(push.err + push.out)) {
        const unique = `${repoName}-${Date.now().toString(36).slice(-6)}`
        ghName = unique
        repoName = unique
        emit(email, 'gh', `الاسم «${repoName.slice(0, -7)}» مستخدم على حسابك — سأنشر باسم فريد «${repoName}»…`)
        push = await makeGh(ghName)
      }
      if (push.code !== 0) throw new Error(`gh فشل: ${push.err.trim().slice(0, 180)}`)
      const out = push.out + push.err
      const m = out.match(/https:\/\/github\.com\/([\w-]+)\/(\S+)/)
      if (m) {
        owner = m[1]
        url = m[0].replace(/\.git$/, '')
        pagesUrl = `https://${owner}.github.io/${m[2].replace(/\.git$/, '')}/`
      } else {
        url = `https://github.com/${owner || 'you'}/${ghName}`
      }
      }
    } else {
      emit(email, 'gh', 'لا يوجد توكن GitHub ولا gh — اعرض التعليمات…')
      audit({ user: email, agent: 'deploy', action: 'deploy', result: 'missing credentials', status: 'error' })
      res.json({ ok: false, error: 'لا يوجد توكن GitHub. افتح الإعدادات وأضف GITHUB_TOKEN (مجاني)، أو سجّل دخول gh CLI.', url: null })
      return
    }

    const readme = path.join(projectDir, 'README.md')
    if (!fs.existsSync(readme)) {
      fs.writeFileSync(readme, `# ${repoName}\n\nGenerated & deployed by **Ghennai** — your free local AI agent.\n\n[التجربة الحية](${pagesUrl || url})\n\n> Private, local, open-source.\n`)
      await run(`git add -A && git -c user.email="${host}@ghennai.local" -c user.name="${name}" commit -m "docs: readme" --allow-empty`, projectDir)
      await run(`git push -u origin main --force`, projectDir)
    }

    let liveUrl = url
    if (owner) {
      emit(email, 'pages', 'تفعيل GitHub Pages…')
      try {
        if (token) {
          const pr = await fetch(`${GITHUB_API}/repos/${owner}/${repoName}/pages`, {
            method: 'POST',
            headers: { Authorization: `token ${token}`, 'Content-Type': 'application/json', 'User-Agent': 'ghennai' },
            body: JSON.stringify({ source: { branch: 'main', path: '/' } }),
          })
          const code = pr.status
          if (code === 201 || code === 409) emit(email, 'pages', 'تم تفعيل GitHub Pages — الرابط يعمل خلال ~1 دقيقة ✓')
          else {
            const txt = await pr.text()
            emit(email, 'pages', `تفعيل Pages (${code}) — ستظهر تلقائيًا قريبًا`)
            void txt
          }
          liveUrl = pagesUrl || url
        } else {
          const pr = await run(`gh api -X POST repos/${owner}/${repoName}/pages -f 'source[branch]=main' -f 'source[path]=/' 2>/dev/null || true`, projectDir)
          if (pr.code === 0) emit(email, 'pages', 'تم تفعيل GitHub Pages — الرابط يعمل خلال ~1 دقيقة ✓')
          else emit(email, 'pages', 'سيتم تفعيل GitHub Pages تلقائيًا قريبًا')
          liveUrl = pagesUrl || url
        }
      } catch {
        emit(email, 'pages', 'رابط المستودع متاح — يمكنك تفعيل Pages من إعدادات المستودع')
        liveUrl = url
      }
    }

    emit(email, 'done', 'تم النشر بنجاح! 🚀')
    emitUser(email, { type: 'deploy_done', url: liveUrl, repoUrl: url })
    if (/github\.io/.test(liveUrl)) verifyLive(email, liveUrl)
    audit({ user: email, agent: 'deploy', action: 'deploy', result: liveUrl, status: 'success' })
    res.json({ ok: true, url: liveUrl, repo: repoName, repoUrl: url })
  } catch (e) {
    const msg = String(e.message || e)
    emit(email, 'error', msg)
    audit({ user: email, agent: 'deploy', action: 'deploy', result: msg, status: 'error' })
    res.status(500).json({ ok: false, error: msg, url: null })
  }
})

export default router